NAME = bsq
SRC = ./srcs/ft_puttruc.c ./srcs/ft_split.c ./srcs/main.c
HEADER = ./includes/

all : $(NAME)

$(NAME) :
	@gcc -Wall -Werror -Wextra $(SRC) -I $(HEADER)

fclean :
	@rm -f $(NAME)

re : fclean all
