# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: anmauffr <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/25 10:26:36 by anmauffr          #+#    #+#              #
#    Updated: 2018/07/26 04:01:02 by anmauffr         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = executable

SRCS = ex*/*.c ./main.c

all:
	@gcc -Wall -Wextra -Werror $(SRCS) -o $(NAME)

clean:
	@rm $(NAME)

re: clean all


